name       : speedcrunch
version    : 0.11
release    : 1
source     :
    - https://bitbucket.org/heldercorreia/speedcrunch/get/0.11.tar.gz : 6d5acd96c5bed2c442e6ec42ff2957637fee9ced8bce94baaaabcaf449500b5e
license    : GPL-2.0
component  : office.maths
summary    : SpeedCrunch is a high-precision scientific calculator. It features a syntax-highlighted scrollable display and is designed to be fully used via keyboard.
description: |
    SpeedCrunch is a high-precision scientific calculator. It features a syntax-highlighted scrollable display and is designed to be fully used via keyboard. Some distinctive features are auto-completion of functions and variables, a formula book, and quick insertion of constants from various fields of knowledge.
builddeps  :
    - pkgconfig(QtGui)
    - pkgconfig(x11)
setup      : |
    ln -s /usr/bin/moc-qt4 /usr/bin/moc
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    mkdir build && pushd build
    %cmake ../src
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    popd
