name       : speedcrunch
version    : 0.12
release    : 2
source     :
    - https://bitbucket.org/heldercorreia/speedcrunch/get/release-0.12.0.tar.bz2 : 59bfc6747060dd15c43c1e9afffdb708c15e3c2a7c36855b83952f33ba451d85
license    : GPL-2.0
component  : office.maths
summary    : SpeedCrunch is a high-precision scientific calculator. It features a syntax-highlighted scrollable display and is designed to be fully used via keyboard.
description: |
    SpeedCrunch is a high-precision scientific calculator. It features a syntax-highlighted scrollable display and is designed to be fully used via keyboard. Some distinctive features are auto-completion of functions and variables, a formula book, and quick insertion of constants from various fields of knowledge.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Help)
    - pkgconfig(glu)
setup      : |
    mkdir build && pushd build
    %cmake ../src
build      : |
    pushd build
    %make
install    : |
    pushd pkg
    sed -i "s:Icon=speedcrunch:Icon=/usr/share/icons/hicolor/scalable/apps/speedcrunch.svg:g" speedcrunch.desktop
    popd
    pushd build
    %make_install
    popd
    pushd gfx
    install -D -m 00644 speedcrunch.svg $installdir/usr/share/icons/hicolor/scalable/apps/speedcrunch.svg
    popd
